name: 003 - AWS Deploy - RDS
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/aws-terraform.yml
    with:
      action: apply
      targets: module.vpc module.rds
      label: RDS
    secrets: inherit
