name: 005 - AWS Destroy - ECS
on:
  workflow_dispatch:
jobs:
  destroy:
    uses: ./.github/workflows/aws-terraform.yml
    with:
      action: destroy
      targets: module.svc_agents module.svc_datalake module.svc_gateway module.ecs
      label: ECS
    secrets: inherit
