name: 005 - AWS Deploy - ECS
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/aws-terraform.yml
    with:
      action: apply
      targets: module.vpc module.bedrock module.ecs
      label: ECS
    secrets: inherit
